import { expect, test } from "vitest";
import request from "supertest";
import { entries } from "../src/db/seeds.js";
import { makeEntrySlug } from "../src/utils/entry-slug.js";
import { createApp } from "../src/app.js";
import { initialize } from "../src/db/initialize.js";
import { seedDatabase } from "../src/db/seed.js";
import { createTestContext } from "./helpers/context.js";

// Museum mineral collection, not the separate autogenerated asset catalog.
const names = ["绿宝石", "海蓝宝石", "红宝石", "紫水晶", "黄水晶", "翡翠", "钻石", "五彩碎片", "石英", "火水晶", "泪晶", "地晶", "透闪石", "黑方石", "重晶石", "青泥石", "方解石", "白云石", "硅钙石", "氟磷灰石", "杰明石", "日光榴石", "绿水镍矿", "铁铅矿", "蓝晶石", "酸性月岩", "孔雀石", "柱星叶石", "柠檬石", "新硅钙石", "雌黄", "石化史莱姆", "雷公蛋", "黄铁矿", "海洋石", "幽灵水晶", "虎眼石", "碧玉", "猫眼石", "赤红猫眼石", "天青石", "大理石", "沙岩", "花岗岩", "玄武岩", "石灰石", "皂石", "赤铁矿", "泥石", "黑曜石", "板岩", "精灵石", "陶瓷碎片"];

test("all 53 museum minerals have one curated page, not only a catalog icon", () => {
  for (const name of names) {
    expect(entries.filter(entry => entry.dataset === "items" && entry.name === name), name).toHaveLength(1);
  }
});

test("new mineral pages expose source, normal price and their own served icon", async () => {
  const context = createTestContext();
  try {
    await initialize(context);
    const app = createApp(context);
    for (const name of names.filter(name => !["五彩碎片", "石英", "火水晶", "泪晶", "地晶"].includes(name))) {
      const entry = entries.find(entry => entry.dataset === "items" && entry.name === name);
      expect(entry, name).toBeDefined();
      const response = await request(app).get(`/wiki/items/${makeEntrySlug(entry)}`);
      expect(response.status, name).toBe(200);
      expect(response.text, name).toContain(entry.attributes.source);
      expect(response.text, name).toContain(entry.attributes.sellPrice);
      expect(entry.attributes["资料来源"], name).toMatch(/^https:\/\/stardewvalleywiki.com\//);
      const detail = await request(app).get(`/api/datasets/items/entries/${makeEntrySlug(entry)}`);
      expect(detail.status, name).toBe(200);
      expect(detail.body.item.image, name).toBe(entry.image);
      expect((await request(app).get(entry.image)).status, entry.image).toBe(200);
    }
    const sql = "SELECT e.id,e.slug,e.name,e.attributes_json FROM dataset_entries e JOIN datasets d ON d.id=e.dataset_id WHERE d.slug='items' ORDER BY e.id";
    const before = context.db.prepare(sql).all();
    seedDatabase(context.db);
    expect(context.db.prepare(sql).all()).toEqual(before);
  } finally { context.close(); }
}, 15000);
